version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3578
      POSTGRES_DB: eventon_db
    ports:
      - "5432:5432"
    networks:
      - eventon_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: eventon_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:3578@postgres:5432/eventon_db?schema=public
    networks:
      - eventon_network
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "npm run prisma:migrate && npm run dev"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - eventon_network

networks:
  eventon_network:

volumes:
  postgres_data:
